---
sample_id:
  type: 'String'
  required: true
  help: 'Sample ID'
reference_fasta:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Absolute path to a reference FASTA file'
exclusion_file:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Absoulte path to an exclusion file'
algorithm:
  type: 'List'
  required: true
  help: 'List of available somatic SV callers'
  default:
    - delly
    - manta
  choices:
    - delly
    - manta
output_dir:
  type: 'Path'
  mode: 'w'
  required: true
  help: 'Absolute path to output directory'
dataset_id:
  type: 'String'
  required: true
  help: 'Dataset identifier'
map_qual:
  type: 'Integer'
  required: true
  default: 20
min_clique_size:
  type: 'Integer'
  required: true
  default: 5
mad_cutoff:
  type: 'Integer'
  required: true
  default: 15
filter_condition:
  type: 'String'
  required: true
  default: "FILTER=='PASS'"
input:
  type: 'InputNamespace'
  required: true
  help: 'Input samples'
  elements:
    BAM:
      type: 'InputBAMNamespace'
      required: true
      help: 'Input BAMs for somatic structural variant calling'
      elements:
        normal:
          type: 'BAMEntryList'
          required: false
          help: 'Input normal BAMs'
        tumor:
          type: 'BAMEntryList'
          required: false
          help: 'Input tumor BAMs'
