@startuml
skinparam SwimlaneTitleFontStyle bold

start

:==Input
---
Input Matched Tumor/Normal BAMs;
:==Input Validation
---
Validate the input BAMs and corresponding index files;

split
partition "DELLY" {
    :==DELLY sSV
    ---
    Call sSVs using DELLY;
    :==Query Sample Name
    ---
    Query Tumor/Normal sample names
    using BCFtools;
    :==Filter sSV
    ---
    Filter out germline SVs using DELLY;
    :==CIRCOS plot
    ---
    Plot CIRCOS for DELLY gSV
    (PNG);
    }

split again
partition "GRIDSS2" {
    :==Preprocess BAM
    ---
    Preprocess Tumor/Normal BAMs;
    :==Breakend Assembly
    ---
    Perform GRIDSS breakend assembly;
    :==GRIDSS2 sSV
    ---
    Call SVs using GRIDSS2;
    :==Filter sSV
    ---
    Filter somatic SV calls;
    }

split again
partition "Manta" {
    :==Manta sSV
    ---
    Call SVs using Manta;
    :==CIRCOS plot
    ---
    Plot CIRCOS for Manta gSV
    (PNG);
    }

split again
partition "SVision" {
    :==SVision SV
    ---
    Call SVs using SVision;
    }
end split
stop
@enduml
